Home/urls.py
from django.conf.urls import include, url

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from .views import HomePage
urlpatterns = [
    url(r"^$",HomePage.as_view(),name='home'),
]

Product/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from .views import NewItem, EditItem, DeleteItem, DetailItem, ListItemSearch, load_subcat


urlpatterns = [
    # Examples:
    # url(r'^$', 'ShoppingCart.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^additem/$',NewItem.as_view(),name="additem"),
    # url(r'^additem/',NewItem.as_view()),

    url(r'^edititem/(?P<pk>\d+)/$',EditItem.as_view(),name="edititem"),
    # url(r'^edititem/',EditItem.as_view()),

    url(r'^deleteitem/(?P<pk>\d+)/$',DeleteItem.as_view(),name="deleteitem"),
    # url(r'^deleteitem/',DeleteItem.as_view()),

    # url(r'^listitem/$',ListItem.as_view(),name="listitem"),
    # url(r'^listitem/',ListItem.as_view()),
    url(r'^listitemsearch/',ListItemSearch.as_view(),name="listitemsearch"),
    # url(r'^listall/',ListItemAll.as_view(),name="listall"),

    url(r'^viewitem/(?P<pk>\d+)/$',DetailItem.as_view(),name="viewitem"),
    # url(r'^viewitem/',DetailItem.as_view()),


    url(r'^ajax/load-cities/$', load_subcat, name='ajax_load_subcat'),
]

Project_Land/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

# from django.views.generic import TemplateView

urlpatterns = [
    # Examples:
    # url(r'^$', 'Project_Land.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^paytest/', TemplateView.as_view(template_name="payment.html"),name="pay"),
    url(r'^oauth/', include('social_django.urls',namespace='social')),
    url(r'^admin/', include(admin.site.urls),name="admin"),
    url(r'^', include('Home.urls',namespace="Home")),
    url(r'^', include('USER.urls',namespace="USER")),
    url(r'^', include('Product.urls',namespace="Product")),
    url(r'^', include('emails.urls',namespace="emails")),
    url(r'^', include('Purchase.urls',namespace="Purchase")),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    # url(r'^admin/logout/$', 'django.contrib.auth.views.logout',{'next_page': '/'},name="admlogout"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Purchase/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .views import ShowServiceView,PurchaseProduct

urlpatterns = [
    url(r"^services/$",ShowServiceView.as_view(),name='services'),
    url(r"^success_purchase/$",PurchaseProduct.as_view(),name='success_purchase'),
]

USER/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf import settings

from .views import LoginUser, ProfileView, RegisterUser, EditUser, DeleteUser,  ChangePasswordUser, activation

from django.views.generic import TemplateView 

urlpatterns = [
    # TODO create a custom view for profile to check whether superuser access
    url(r'^login/$',LoginUser.as_view(),name="login"),
    url(r'^logout/$',auth_views.logout,{'next_page': settings.LOGOUT_REDIRECT_URL},name="logout"),
    url(r'^register/$',RegisterUser.as_view(),name='register'),
    url(r'^activate/(?P<key>.+)/$',activation,name="activate"),
    url(r'^activation_success/$',TemplateView.as_view(template_name="activation_success.html"),name="activate_success"),
    
    url(r'^profile/$',ProfileView.as_view(),name="profile"),
    url(r'^changepassword/$',ChangePasswordUser.as_view(),name="changepassword"),
    url(r'^editprofile/$',EditUser.as_view(),name="editprofile"),
    
    url(r'^delete/$',DeleteUser.as_view(),name='delete'),

]
    

Home/models.py
from django.db import models

# Create your models here.


from geoposition.fields import GeopositionField

class PointOfInterest(models.Model):
    name = models.CharField(max_length=100)
    position = GeopositionField()

    

Home/forms.py
from django import forms 

from .models import PointOfInterest


class ff(forms.ModelForm):
	class Meta:
		model = PointOfInterest
		fields = "__all__"

Home/views.py
from django.shortcuts import render, redirect

from django.views.generic import View, FormView
from Product.models import Product
from django.core.urlresolvers import reverse
from .models import PointOfInterest
# Create your views here.
from .forms import ff
from emails.forms import MailsForm

def mod_response(response):
    response["Cache-Control"] = "no-cache, no-store, must-revalidate" # HTTP 1.1.
    response["Pragma"] = "no-cache" # HTTP 1.0.
    response["Expires"] = "0" # Proxies.
    return response

class HomePage(View):
    template_name="Home/home2.html"
    def get(self,request):
        if request.user.is_authenticated():
            if request.user.is_superuser:
                return mod_response(redirect('/admin'))
        context = {"contact":MailsForm(),'form':ff()}
        return mod_response(render(request,self.template_name,context))

    def post(self,request):
        request.session['yes_mail'] = True
        request.session['mail_type'] = 0
        request.session['reciever'] = "crayoneater2121@gmail.com"
        request.session['subject'] = "[LootMarket] Contact by user to admin"
        request.session['sender'] = request.POST.get('sender')
        request.session['message'] = request.POST.get('message')
        return mod_response(redirect(reverse('emails:newmail')))

Home/templates/Home/home2.html
{% extends "base2.html" %}
{% load static %}
{%block title%}LootMarket - Home{%endblock%}
{%block headstyle%}
<style>
    .top-header {
        width: 100%;
        position: fixed;
        display: flex;
        justify-content: center;
        z-index: 6;
        height: 140px;
        background: linear-gradient(0deg, rgba(92, 101, 201, 0.1) 0%, #746087 100%);
    }
    .header-content {
        width: 85%;
        position: absolute;
        height: 140px;
        padding-top: 20px;
    }




    .home-link {
        display: flex;
        
        position: relative;
    }
    .ull {
        flex: 1;
        margin: 0 auto;
    }
    .home-link-a,.home-link-a:visited{
        width: 294px;
        margin: 0 auto;
        display: block;
        list-style: none;
        font-size: 2.8rem;
        color: white;
        text-align: center;
        text-decoration: none; 
    }



    .glob-links {
        
        position: fixed;
        top: 0;
        left: 0;
        width: 0;
        height: 100%;
        overflow-x: hidden;
        background-color: #000000cc;
        display: block;
    }
    .close-bar {
        width: 60px;
        color: white;
        font-size: 2.8rem;
        position: fixed;
        left: 20px;
        top: 10px;
        cursor: pointer;
    }
    .llinks {
        margin-top: 100px;
    }

    .link-set,.link-set * {
        text-align: center;
        text-decoration: none;
        color: white;
        /*margin: 10px 0;*/
    }
    .link-set {
        width: 100%;
        display: block;
        padding: 0;
        margin: 0;
        list-style: none;
        width: 100%;
    }
    .link-set > li {
        /*margin: 10px;*/
        height: 100%;
        width: 100%;
        margin-bottom: 30px;
        position: relative; 
        display: block;  
    }
    .link-set a,.link-set a:visited {
        position: relative;
        height: 100%;
        width: 30%;
        color: white;
        padding-bottom: 15px;
        display: inline;
        text-align: center;
        text-decoration: none;
    }
    .link-set a::before {
        left: 0;
        right: 0;
        bottom: 0;
        height: 0;
        content: "";
        position: absolute;
        transition: 0.1s height;
        background-color: white;
        border-top-left-radius: 2px;
        border-top-right-radius: 2px;
    }
    .link-set a:hover::before {
        height: 5px; 
    }
    .side-right {
        flex-direction: row-reverse;
        margin-left: auto;
    }

    @media only screen and (min-width: 450px) {
        .home-link-a {
            font-size: 4rem !important;
        }
        .close-bar{
            font-size: 4em;
        }
    }



    @media only screen and (min-width: 950px) {
        .glob-links, ..glob-links * {
            all:initial;
        }
        .home-link {
            z-index: 6;
            width: 350px;
            margin: 0 auto;
        }
        .glob-links {
            z-index: 5;
            position: absolute;
            background-color: #00000000;
            width: 100%;
            height: 90px;
            overflow:inherit;
        }
        .close-bar{
            display: none;
        }
        .llinks {
            display: flex;
            flex-flow: row nowrap;
            position: absolute;
            padding: 0;
            margin: 0;
            height: 100%;
            width: 100%;
            align-content: stretch;
        }
        .link-set {
            display: flex;
            list-style: none;
            align-items: stretch;
            justify-content: flex-start;
            flex-flow: row nowrap;
            width: 21%;
            margin-top: 10px;
        }
        .link-set > li {
            flex-basis: 140px;
            margin: 0 10px;
            height: 51px;
            margin-top: 9px; 
            position: relative;   
        }
        
    }

    
</style>
<style>
    .landing {
        z-index: 0;
        position: fixed;
        top: 0;
        left: 0;
        height: 100%;
        width: 100%;
        background-color: #000;
        background: url("{% static "Home/pic9.jpg" %}") fixed no-repeat center center;
        background-size: cover;
    }
    /*.ssfm{
        position: relative;
        top: 10%;
        opacity: 0;
        visibility: hidden;
        width: 100%;
    }*/
    
</style>
<style>
    .intro {
        z-index: 2;
        position: absolute;
        top: 100%;
        left: 0;
        right: 0;
        width: 100%;
        background-color: rgba(255,255,255,0.3);
        border: ridge 5px black;
        min-height: calc(100% - 140px);
        display: flex;
        flex-direction: column;
    }
    .prompt {
        margin: 0;
        padding: 0;
        z-index: 1;
        height: 50px;
        bottom: 0px;
        left: 0;
        right: 0;
        position: fixed;
        text-align: center;
        font-size: 30px;
        color: white;
        text-shadow: 0 0 5px black;
        animation: bob 1s ease-in-out infinite alternate;
    }
    @keyframes bob {
        from {bottom: 0px;}
        to {bottom: -10px;}
    }

    .overfl {
        flex: 1;
        width: 100%;
        display: flex;
        /*align-items: stretch;*/
        flex-direction: column;
        justify-content: space-evenly;
        /*padding-top: 20px;*/
        /*padding-bottom: 20px;*/
        justify-content: space-evenly;
        border-bottom: solid 2px #222;
    }
    .overfl:last-child {
        flex: none;
        border-bottom: none;
        padding: 0;
        margin: 0;
        width: 100%;
        height: 90px;
        background-color: rgb(198, 195, 255);
    }
    .overfl > p {
        width: 85%;
        /*margin: 0;*/
        margin: 20px auto;
    }
    table {
        width: 90%;
    }
    .contact-form,.contact-form input,.contact-form textarea {
        width: 100%;
    }
    .features {
        margin: 20px auto;
        padding: 10px;
        width: 80%;
    }
    .ll {
        justify-content: flex-start;
    }
    .ono {
        border : solid 2px #ccc;
        background-color: rgb(198, 195, 255);
    }

    @media only screen and (min-width: 600px) {
        .overfl {
            flex-direction: row;
            margin-top: 20px;
            padding-bottom: 20px;
        }
        .features {
            text-align: left;
            border : solid 2px #ccc;
            padding: 10px 10px;
            margin:0;
            width: 20%;
        }
        .overfl > p {
        width: 85%;
        height: 110px;
        padding: 5px;
        margin: 0 auto;
    }
    }
    @media only screen and (min-width: 450px) {
        .contact-form {
            overflow-x: hidden;
            width: 430px;
        }

        .contact-form input,.contact-form textarea {
            width: calc(450px - 69px);
        }
    }

    .search-bar {
        position: absolute;
        margin: 0;
        padding: 0;
        top: 0;
        left: 0;
        border: 0px solid #9D07BA;
        border-top-left-radius: 4px;
        border-bottom-left-radius: 4px; 
        background-color: white;
        height: 100%;
        width: 90%;
        font-size: 16px;
        padding: 12px 20px 12px 20px;
    }
    .search-button {
        position: absolute;
        margin: 0;
        padding: 0;
        top: 0;
        right: 0;
        height: 100%;
        border: none;
        width: 10%;
        border-left: 1px solid #000;
        background-color: #fff;
        border-top-right-radius: 4px;
        border-bottom-right-radius: 4px; 
    }
    .ssfm {
        position: relative;
        border:1px solid #00000044;
        border-radius: 4px;
        top: 60%;
        left: calc(25%/2);
        height: 40px;
        width: 75%;
        opacity: 0;
    }
</style>
{%endblock%}
{% block headscript %}
{% endblock %}
{%block content%}
<header class="top-header">
    <nav class="header-content">
        <div class="home-link">
            <div class="ull">
                <a href="{% url 'Home:home'%}" class="home-link-a">LootMarket</a>
            </div>
        </div>
        <div class="glob-links">
            <span class="close-bar">&#9776;</span>
            <div class="llinks">
                <ul class="link-set side-left">
                    <li><a href="{% url 'Purchase:services'%}">Services</a></li>
                    <li><a href="{% url 'Product:listitemsearch'%}?qry=">Listings</a></li>
                </ul>
                <ul class="link-set side-right">
                    {% if user.is_authenticated%}
                    <li><a href="{% url 'USER:profile'%}">Profile</a></li>
                    <li><a href="{% url 'USER:logout'%}">Logout</a></li>
                    {%else%}
                    <li><a href="{% url 'USER:login'%}">Login</a></li>
                    <li><a href="{% url 'USER:register'%}">Register</a></li>
                    {%endif%}
                </ul>
            </div>
        </div>
    </nav>
</header>
<!--  -->
<main class="landing">
    <form method="get" action="{%url 'Product:listitemsearch' %}" class="ssfm">
        <input name="qry" class="search-bar">
        <button type="submit" class="search-button">
            <i class="material-icons">search</i>
        </button>
    </form>
</main>
<!--  -->
<div class="prompt">▼</div>
<!--  -->
<section id="main-section" class="intro">
    <section class="overfl">
        <div class="features ono">Lorem ipsum dolor sit amet, consectetur adipisicing elit. At, cum?</div>
        <div class="features ono">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum, magni!</div>
        <div class="features ono">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, facere.</div>
        <div class="features ono">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima, illo!</div>
    </section>
    <section class="overfl">
        <p class="ono">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa laudantium repellat doloremque voluptate aspernatur vel error hic quaerat optio unde distinctio provident nostrum, obcaecati amet, modi quis cumque fugit incidunt ab voluptatibus tempora omnis. Nihil repellendus, fuga libero, illum provident quam iste aliquam delectus corporis nam! Minima rem, quia autem.</p>
    </section>
    <section class="overfl ll">
        <form method="post" action="" class="contact-form">
            {% csrf_token %}
            <table>
                {{contact.as_table}}
                <tr>
                    <td></td>
                    <td>
                        <button type="submit">Submit</button>
                    </td>
                </tr>
            </table>
        </form>
    </section>
    <section class="overfl">
        ADDRESS CONTACT AND OTHER RELATED FOOTER INFO
    </section>
</section>
{%endblock%}
{% block bodyscript %}
<script>
$(window).on('load', function() {
    console.log("hit");
    $(".ssfm").animate({
        top: "-=10%",
        opacity: "1"
    }, 1100);
});
$(function() {
    var bOpened = false;
    var bResize = false;
    var hh = $(window).height();
    var ww = $(window).width();

    $(".close-bar").click(function() {
        if (!bOpened) {
            bOpened = true;
            $(".glob-links").animate({
                width: "200px"
            }, 100, "linear");
            $(this).delay(25).animate({
                left: "160px"
            }, 100, "linear").html("&times;");
        } else {
            bOpened = false;
            $(".glob-links").animate({
                width: "0"
            }, 100, "linear");
            $(this).animate({
                left: "20px"
            }, 100, "linear").html("&#9776;");
        }
    });
    $(window).resize(function() {
        var tw = $(window).width();
        var th = $(window).height();
        if (!bResize && tw >= 950 && ww < 950) {
            bResize = true;
            $(".glob-links").stop(true, true).css("width", "100%");
            if (bOpened) {
                $(".close-bar").css("left", "30px").html("&#9776;");
                bOpened = !bOpened;
            }
        } else if (bResize && tw < 950 && ww >= 950) {
            $(".glob-links").stop(true, true).css("width", "0");
            bResize = false;
        }
        ww = tw;
        hh = th;
    });

    var fscroll = false;
    var bScrolled = false;


    $(".prompt").click(function() {
        $(".prompt").fadeOut("fast");
        $(".ssfm").fadeOut("fast");
        $('html').animate({ scrollTop: (hh - 140) }, 300);
        bScrolled = true;
    });
    $(document).scroll(function() {
        var mn_pos = $(this).scrollTop();
        if (!fscroll && !bScrolled) {
            $(".prompt").fadeOut("fast");
            $(".ssfm").fadeOut("fast");
            $('html').animate({ scrollTop: (hh - 140) }, 300);
            bScrolled = true;
        } else if (!bScrolled && mn_pos < (hh - 140)) {
            bScrolled = true;
            $('html').animate({ scrollTop: 0 }, 300);
            $(".prompt").fadeIn("fast");
            $(".ssfm").fadeIn("fast");
        }
        if (!fscroll && mn_pos == (hh - 140)) {
            bScrolled = false;
            fscroll = true;
        }
        if (fscroll && !mn_pos) {
            bScrolled = false;
            fscroll = false;
        }

    });

});
</script>
{% endblock %}