Home/urls.py
from django.conf.urls import include, url

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from .views import HomePage
urlpatterns = [
    url(r"^$",HomePage.as_view(),name='home'),
]

Product/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from .views import NewItem, EditItem, DeleteItem, DetailItem, ListItemSearch, load_subcat


urlpatterns = [
    # Examples:
    # url(r'^$', 'ShoppingCart.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^additem/$',NewItem.as_view(),name="additem"),
    # url(r'^additem/',NewItem.as_view()),

    url(r'^edititem/(?P<pk>\d+)/$',EditItem.as_view(),name="edititem"),
    # url(r'^edititem/',EditItem.as_view()),

    url(r'^deleteitem/(?P<pk>\d+)/$',DeleteItem.as_view(),name="deleteitem"),
    # url(r'^deleteitem/',DeleteItem.as_view()),

    # url(r'^listitem/$',ListItem.as_view(),name="listitem"),
    # url(r'^listitem/',ListItem.as_view()),
    url(r'^listitemsearch/',ListItemSearch.as_view(),name="listitemsearch"),
    # url(r'^listall/',ListItemAll.as_view(),name="listall"),

    url(r'^viewitem/(?P<pk>\d+)/$',DetailItem.as_view(),name="viewitem"),
    # url(r'^viewitem/',DetailItem.as_view()),


    url(r'^ajax/load-cities/$', load_subcat, name='ajax_load_subcat'),
]

Project_Land/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

# from django.views.generic import TemplateView

urlpatterns = [
    # Examples:
    # url(r'^$', 'Project_Land.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^paytest/', TemplateView.as_view(template_name="payment.html"),name="pay"),
    url(r'^oauth/', include('social_django.urls',namespace='social')),
    url(r'^admin/', include(admin.site.urls),name="admin"),
    url(r'^', include('Home.urls',namespace="Home")),
    url(r'^', include('USER.urls',namespace="USER")),
    url(r'^', include('Product.urls',namespace="Product")),
    url(r'^', include('emails.urls',namespace="emails")),
    url(r'^', include('Purchase.urls',namespace="Purchase")),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    # url(r'^admin/logout/$', 'django.contrib.auth.views.logout',{'next_page': '/'},name="admlogout"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Purchase/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .views import ShowServiceView,PurchaseProduct

urlpatterns = [
    url(r"^services/$",ShowServiceView.as_view(),name='services'),
    url(r"^success_purchase/$",PurchaseProduct.as_view(),name='success_purchase'),
]

USER/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf import settings

from .views import LoginUser, ProfileView, RegisterUser, EditUser, DeleteUser,  ChangePasswordUser, activation

from django.views.generic import TemplateView 

urlpatterns = [
    # TODO create a custom view for profile to check whether superuser access
    url(r'^login/$',LoginUser.as_view(),name="login"),
    url(r'^logout/$',auth_views.logout,{'next_page': settings.LOGOUT_REDIRECT_URL},name="logout"),
    url(r'^register/$',RegisterUser.as_view(),name='register'),
    url(r'^activate/(?P<key>.+)/$',activation,name="activate"),
    url(r'^activation_success/$',TemplateView.as_view(template_name="activation_success.html"),name="activate_success"),
    
    url(r'^profile/$',ProfileView.as_view(),name="profile"),
    url(r'^changepassword/$',ChangePasswordUser.as_view(),name="changepassword"),
    url(r'^editprofile/$',EditUser.as_view(),name="editprofile"),
    
    url(r'^delete/$',DeleteUser.as_view(),name='delete'),

]
    

USER/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

# Create your models here.

class cUser(AbstractUser):
	#add additional fields here or use a proxy model
	
	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['first_name']
	def __str__(self):
		return self.first_name

cUser._meta.get_field('email')._unique = True
cUser._meta.get_field('username')._unique = False

class ActivationKey(models.Model):
	user = models.OneToOneField(cUser,related_name="key",blank=False,null=False,on_delete=models.CASCADE)
	hash_key = models.CharField(max_length=200,blank=False,null=False)
	def __str__(self):
		return str(self.user.email)

USER/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import cUser, ActivationKey

from django.utils.crypto import get_random_string
from django.core.mail import send_mail
import hashlib




def generate_activation_key(username):
    chars = 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)'
    secret_key = get_random_string(20, chars)
    return hashlib.sha256((secret_key + username).encode('utf-8')).hexdigest()

def send_activation_mail(cryptstr,uname):
	send_mail("[LootMarket] Activate your new account","Welcome,\n\nThank you for registering with us.\n\nTo activate your newly created account please click the link below, if the link cannot be clicked, copy paste it into your browser url bar.\n\nhttp://bitDaft.pythonanywhere.com/activate/"+cryptstr+"\n\nWe hope to see you around!!\n\nRegards,\nLootMarket",settings.EMAIL_HOST_USER,[uname])




class cUserCreationForm(UserCreationForm):
	def __init__(self, *args, **kwargs):
	    super(cUserCreationForm, self).__init__(*args, **kwargs)
	    self.fields['first_name'].label = "Full Name"

	UserCreationForm.password2 = None
	class Meta(UserCreationForm.Meta):
		model = cUser
		fields = ['first_name','email','password1',]
		# fields = '__all__'

	def clean_password2(self):
		password1 = self.cleaned_data.get("password1")
		if password1:
			raise forms.ValidationError(
				self.error_messages['password_empty'],
				code='password_empty',
			)
		return password1

		
	def save(self, commit=True):
		user = super(cUserCreationForm, self).save(commit=False)
		user.is_active=False
		if commit:
			user.save()
			cryptstr = generate_activation_key(user.username)
			key = ActivationKey.objects.create(user=user,hash_key=cryptstr)
			key.save()
			send_activation_mail(cryptstr,user.email)
		return user

class cUserChangeForm(UserChangeForm):
	UserChangeForm.password = None
	class Meta:
		model = cUser
		fields = ['email','first_name']

	def __init__(self, *args, **kwargs):
	    super(cUserChangeForm, self).__init__(*args, **kwargs)
	    self.fields['first_name'].label = "Full Name"

USER/views.py
import urllib
import urllib2
import json

from django.conf import settings

from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse

from django.views.generic import View, TemplateView, CreateView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate,login

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

from .forms import cUserCreationForm, cUserChangeForm
from .models import cUser, ActivationKey
from Product.models import Product 

# Create your views here.

def mod_response(response):
	response["Cache-Control"] = "no-cache, no-store, must-revalidate" # HTTP 1.1.
	response["Pragma"] = "no-cache" # HTTP 1.0.
	response["Expires"] = "0" # Proxies.
	return response

class RegisterUser(CreateView):
	template_name = 'USER/login.html'
	model = cUser
	form_class = cUserCreationForm
	success_url = '/'
	def get(self,request):
		if request.user.is_authenticated():
			return mod_response(redirect(reverse('Home:home')))
		else:
			return mod_response(super(RegisterUser,self).get(self,request))
	def post(self,request):
		form = cUserCreationForm(request.POST)
		obj = cUser.objects.filter(email=request.POST.get('email')).first()
		if obj and not obj.is_active:
			obj.delete()
		elif obj and obj.is_active:
			return mod_response(redirect(reverse('Home:home')))
		return_url = request.GET.get('returnto')
		print(return_url,"/"*30)
		if return_url:
			print('*'*30)
			request.session['reg_return_url'] = return_url
			self.success_url = "/login"
		return mod_response(super(RegisterUser,self).post(self,request))

class LoginUser(View):
	def get(self,request):
		template_name = 'USER/login.html'
		context = {'form':AuthenticationForm(),'error':None,'ff':'log'}
		if request.user.is_authenticated():
			return mod_response(redirect(reverse('Home:home')))
		return mod_response(render(request,template_name,context))

	def post(self,request):
		if request.user.is_authenticated():
			return mod_response(redirect(reverse('Home:home')))
		f1 = request.POST.get('username')
		f2 = request.POST.get('password')
		user = authenticate(username=f1,password=f2)
		if user:
			if user.is_active:
				recaptcha_response = request.POST.get('g-recaptcha-response')
				url = 'https://www.google.com/recaptcha/api/siteverify'
				values = {
				'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
				'response': recaptcha_response
				}
				data = urllib.urlencode(values)
				req = urllib2.Request(url, data)
				response = urllib2.urlopen(req)
				result = json.load(response)
				if True and result['success']:
					login(request,user)
					callback_url = request.GET.get('returnto')
					if 'reg_return_url' in request.session:
						callback_url = request.session['reg_return_url']
						del request.session['reg_return_url']
					if callback_url:
						return mod_response(redirect(callback_url))
					return mod_response(redirect(reverse('Home:home')))
				else:
					print("//"*20,"Invalid reCaptcha")
		template_name = 'USER/login.html'
		context = {'form':AuthenticationForm(),'error':'Email or password incorrect!!'}
		return mod_response(render(request,template_name,context))

class ProfileView(ListView):
	template_name = "USER/profile.html"
	model = Product
	context_object_name = 'object'
	
	def get(self,request):
		if request.user.is_authenticated():
			if request.user.is_superuser:
				return mod_response(redirect(reverse('Home:home')))
			return mod_response(super(ProfileView,self).get(self,request))
		return mod_response(redirect(reverse('Home:home')))

	def get_queryset(self):
		rval = super(ProfileView,self).get_queryset()
		rval = rval.filter(user=self.request.user)
		return rval

class EditUser(UpdateView):
	template_name = 'USER/editprofile.html'
	model = cUser
	form_class = cUserChangeForm
	def get(self,request):
		if request.user.is_authenticated():
			if request.user.is_superuser:
				return mod_response(redirect(reverse('Home:home')))
			return mod_response(super(EditUser,self).get(self,request))
		return mod_response(redirect(reverse('Home:home')))

	def get_success_url(self):
		return reverse('USER:profile')

	def get_object(self, queryset=None):
		return self.request.user

class DeleteUser(DeleteView):
	model = cUser
	template_name = "Product/delitem.html"
	def get(self,request):
		if request.user.is_authenticated():
			if request.user.is_superuser:
				return mod_response(redirect(reverse('Home:home')))
			return mod_response(super(DeleteUser,self).get(self,request))
		return mod_response(redirect(reverse('Home:home')))

	def post(self,request):
		user = request.user
		if user.is_authenticated():
			user.is_active = False
			user.save()
			return mod_response(redirect(reverse('USER:logout')))
		return mod_response(redirect(reverse('Home:home')))

	def get_success_url(self):
		return '/'

	def get_object(self, queryset=None):
		return self.request.user

class ChangePasswordUser(View):
	template_name = 'USER/changepass.html'
	def get(self,request):
		if request.user.is_authenticated():
			if request.user.is_superuser:
				return mod_response(redirect(reverse('Home:home')))
			form = PasswordChangeForm(request.user)
			return mod_response(render(request,self.template_name, {'form': form}))
		return mod_response(redirect(reverse('Home:home')))

	def post(self,request):
		if request.user.is_authenticated():
			form = PasswordChangeForm(request.user,request.POST)
			if form.is_valid():
				user = form.save()
				update_session_auth_hash(request, user)
				return mod_response(redirect(reverse('USER:profile')))
		return mod_response(redirect(reverse('USER:changepassword')))

def activation(request,key):
	obj = ActivationKey.objects.filter(hash_key=key).first()
	if obj:
		u = obj.user
		u.is_active = True
		obj.delete()
		u.save()
		return mod_response(redirect('activate_success'))
	return mod_response(redirect(reverse('Home:home')))

USER/templates/USER/profile.html
{% extends "base2.html" %}
{% load static %}
{%block title%}LootMarket - Profile{%endblock%}
{%block headstyle%}
<style>    
    .top-header {
        width: 100%;
        position: fixed;
        display: flex;
        justify-content: center;
        z-index: 6;
        height: 140px;
        background: linear-gradient(0deg, rgba(255, 255, 255, 0.1) 0%, #e4efcd 100%);
    }
    .header-content {
        width: 85%;
        position: absolute;
        height: 140px;
        padding-top: 20px;
    }
    .header-content a {
        /*text-shadow: 0px 0px 3px black;*/
        /*color: black !important;*/
    }



    .home-link {
        display: flex;
        
        position: relative;
    }
    .ull {
        flex: 1;
        margin: 0 auto;
    }
    .home-link-a,.home-link-a:visited{
        width: 294px;
        margin: 0 auto;
        display: block;
        list-style: none;
        font-size: 2.8rem;
        color: black;
        text-align: center;
        text-decoration: none; 
    }



    .glob-links {
        z-index: 5;
        position: fixed;
        top: 0;
        left: 0;
        width: 0;
        height: 100%;
        overflow-x: hidden;
        background-color: #000000cc;
        display: block;
    }
    .close-bar {
        width: 60px;
        color: black;
        font-size: 2.8rem;
        position: fixed;
        left: 20px;
        top: 10px;
        cursor: pointer;
    }
    .llinks {
        margin-top: 100px;
    }

    .link-set,.link-set * {
        text-align: center;
        text-decoration: none;
        /*margin: 10px 0;*/
    }
    .link-set {
        width: 100%;
        display: block;
        padding: 0;
        margin: 0;
        list-style: none;
    }
    .link-set > li {
        /*margin: 10px;*/
        height: 100%;
        width: 100%;
        margin-bottom: 30px;
        position: relative; 
        display: block;  
    }
    .link-set a,.link-set a:visited {
        position: relative;
        height: 100%;
        /*width: 30%;*/
        display: block;
        color: white;
        padding-bottom: 15px;
        /*display: inline;*/
        text-align: center;
        text-decoration: none;
    }
    .link-set a::before {
        left: 0;
        right: 0;
        bottom: 0;
        height: 0;
        content: "";
        position: absolute;
        transition: 0.1s height;
        background-color: white;
        border-top-left-radius: 2px;
        border-top-right-radius: 2px;
    }
    .link-set a.bdd::before {
        bottom: -25px;
        height: 0;
        content: "";
    }
    .link-set a:hover::before {
        height: 5px; 
    }
    .side-right {
        flex-direction: row-reverse;
        margin-left: auto;
    }
    .whh {
        color: white;
    }
    @media only screen and (min-width: 450px) {
        .home-link-a {
            font-size: 4rem !important;
        }
        .close-bar{
            font-size: 4em;
        }
    }



    @media only screen and (min-width: 950px) {
        .glob-links, ..glob-links * {
            all:initial;
        }
        .home-link {
            z-index: 6;
            width: 350px;
            margin: 0 auto;
        }
        .glob-links {
            position: absolute;
            background-color: #00000000;
            width: 90%;
            height: 90px;
            overflow:inherit;
        }
        .close-bar{
            display: none;
        }
        .llinks {
            display: flex;
            flex-flow: row nowrap;
            position: absolute;
            padding: 0;
            margin: 0;
            height: 100%;
            width: 100%;
            align-content: stretch;
        }
        .link-set {
            display: flex;
            list-style: none;
            align-items: stretch;
            justify-content: flex-start;
            flex-flow: row nowrap;
            width: 21%;
            margin-top: 10px;
        }
        .link-set > li {
            flex-basis: 140px;
            margin: 0 10px;
            height: 51px;
            margin-top: 9px; 
            position: relative;   
        }
        .link-set a,.link-set a:visited {
            color: black;
        }
        .link-set a::before {
            background-color: black;
        }
        
    }

</style>
<style>
.details {
    position: absolute;
    top: 140px;
    left: 0;
    right: 0;
    bottom: 0;
    padding-left: 20px;
    background: url("{% static "USER/pic4.png" %}") fixed no-repeat center center;
    background-size: cover;
    overflow-y: scroll;
}

.links {
    font-size: 25px;
    float: right;
    text-decoration: none;
    display: fixed;
}

.links>a {
    display: fixed;
    text-decoration: none;
}

.links:after {
    content: "";
    clear: both;
}

    .search-item {
        margin: 5px 10px 10px 10px ;
        font-size: 12px;
        padding-top: 10px;
        padding-bottom: 15px;
        padding-left: 10px;   
        /*height: 130px;*/
        border-bottom: 2px solid #555;     
    }
    .search-item:last-child {
        border-bottom: none;     
    }
    .search-item * {
        text-decoration: none;
    }
    .search-item a,.search-item a:visited:active {
        color: black;
    }
    .prod_img {
        height: 100px;
        margin-right: 20px;
    }
    .mn {
        font-weight: bold;
    }
    .tti {
        display: block;
        height: 100px;
        width: 170px;
    }
    .tth {
        display: block;
    }
    .ttt {
        display: block;
    }
    @media only screen and (min-width: 450px) {
        .tti,.ttt {
            display: inline-block;
        }
        .tti {
            
        }
        .ttt {
            width: calc(100% - 200px); 
            vertical-align: top;
        }
    }
.edit-link {
    font-size: 16px;
    text-decoration: underline; 
}
</style>
{%endblock%}
{%block content%}
<header class="top-header">
    <nav class="header-content">
        <div class="home-link">
            <div class="ull">
                <a href="{% url 'Home:home'%}" class="home-link-a">LootMarket</a>
            </div>
        </div>
        <div class="glob-links">
            <span class="close-bar">&#9776;</span>
            <div class="llinks">
                <ul class="link-set side-left">
                    <li><a href="{% url 'Purchase:services'%}">Services</a></li>
                    <li><a href="{% url 'Product:listitemsearch'%}?qry=">Listings</a></li>
                </ul>
                <ul class="link-set side-right">
                    {% if user.is_authenticated%}
                    <li><a href="{% url 'Product:additem'%}" class="bdd">New Product</a></li>
                    <li><a href="{%url 'USER:editprofile'%}" class="bdd">Edit Profile</a></li>
                    <li><a href="{% url 'USER:logout'%}">Logout</a></li>
                    {%endif%}
                </ul>
            </div>
        </div>
    </nav>
</header>
<!--  -->
<div class="details">
    {% if user.is_authenticated%}
    <p>Full name : {{user.first_name}}</p>
    <p>Email : {{user.email}}</p>
    {%for i in object%}
        <div class="search-item">
            <div class="tth">
                <a href="{%url 'Product:viewitem' pk=i.id %}">
                    <h1 class="mn">{{i.product_name}}</h1>
                </a>
            </div>
            <div>
                <div class="tti">
                    <a href="{%url 'Product:viewitem' pk=i.id %}">
                    <img class="prod_img" src="{{ i.product_image.url }}" alt="">
                </a>
                </div>
                <table class="ttt">
                    <tr>
                        <td>
                            Description
                        </td>
                        <td>
                            : {{i.product_description|truncatewords:13}}
                        </td>
                    </tr>
                    <tr class="ad-info">
                        <td>
                            Category
                        </td>
                        <td>
                            : {{i.category}}
                        </td>
                    </tr>
                    <tr class="ad-info">
                        <td>
                            Subcategory
                        </td>
                        <td>
                            : {{i.subcategory}}
                        </td>
                    </tr>
                </table>
                <p>
                    <a class="edit-link" href="{%url 'Product:edititem' pk=i.id%}">EDIT</a>
                </p>
            </div>
        </div>
        {%endfor%}
    {%endif%}
</div>
{%endblock%}



{% block bodyscript %}
<script>
$(function() {
    var bOpened = false;
    var bResize = false;
    var ww = $(window).width();

    $(".close-bar").click(function() {
        if (!bOpened) {
            bOpened = true;
            $(".glob-links").animate({
                width: "200px"
            }, 100, "linear");
            $(this).delay(25).animate({
                left: "160px"
            }, 100, "linear").html("&times;");
        } else {
            bOpened = false;
            $(".glob-links").animate({
                width: "0"
            }, 100, "linear");
            $(this).animate({
                left: "20px"
            }, 100, "linear").html("&#9776;");
        }
            $(this).toggleClass("whh");
    });
    $(window).resize(function() {
        var tw = $(window).width();
        if (!bResize && tw >= 950 && ww < 950) {
            bResize = true;
            $(".glob-links").stop(true, true).css("width", "90%");
            if (bOpened) {
                $(".close-bar").toggleClass("whh");
                $(".close-bar").css("left", "30px").html("&#9776;");
                bOpened = !bOpened;
            }
        } else if (bResize && tw < 950 && ww >= 950) {
            $(".glob-links").stop(true, true).css("width", "0");
            bResize = false;
        }
        ww = tw;
    });

});
</script>
{% endblock %}