Home/urls.py
from django.conf.urls import include, url

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from .views import HomePage
urlpatterns = [
    url(r"^$",HomePage.as_view(),name='home'),
]

Product/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from .views import NewItem, EditItem, DeleteItem, DetailItem, ListItemSearch, load_subcat


urlpatterns = [
    # Examples:
    # url(r'^$', 'ShoppingCart.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^additem/$',NewItem.as_view(),name="additem"),
    # url(r'^additem/',NewItem.as_view()),

    url(r'^edititem/(?P<pk>\d+)/$',EditItem.as_view(),name="edititem"),
    # url(r'^edititem/',EditItem.as_view()),

    url(r'^deleteitem/(?P<pk>\d+)/$',DeleteItem.as_view(),name="deleteitem"),
    # url(r'^deleteitem/',DeleteItem.as_view()),

    # url(r'^listitem/$',ListItem.as_view(),name="listitem"),
    # url(r'^listitem/',ListItem.as_view()),
    url(r'^listitemsearch/',ListItemSearch.as_view(),name="listitemsearch"),
    # url(r'^listall/',ListItemAll.as_view(),name="listall"),

    url(r'^viewitem/(?P<pk>\d+)/$',DetailItem.as_view(),name="viewitem"),
    # url(r'^viewitem/',DetailItem.as_view()),


    url(r'^ajax/load-cities/$', load_subcat, name='ajax_load_subcat'),
]

Project_Land/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

# from django.views.generic import TemplateView

urlpatterns = [
    # Examples:
    # url(r'^$', 'Project_Land.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^paytest/', TemplateView.as_view(template_name="payment.html"),name="pay"),
    url(r'^oauth/', include('social_django.urls',namespace='social')),
    url(r'^admin/', include(admin.site.urls),name="admin"),
    url(r'^', include('Home.urls',namespace="Home")),
    url(r'^', include('USER.urls',namespace="USER")),
    url(r'^', include('Product.urls',namespace="Product")),
    url(r'^', include('emails.urls',namespace="emails")),
    url(r'^', include('Purchase.urls',namespace="Purchase")),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    # url(r'^admin/logout/$', 'django.contrib.auth.views.logout',{'next_page': '/'},name="admlogout"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Purchase/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .views import ShowServiceView,PurchaseProduct

urlpatterns = [
    url(r"^services/$",ShowServiceView.as_view(),name='services'),
    url(r"^success_purchase/$",PurchaseProduct.as_view(),name='success_purchase'),
]

USER/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf import settings

from .views import LoginUser, ProfileView, RegisterUser, EditUser, DeleteUser,  ChangePasswordUser, activation

from django.views.generic import TemplateView 

urlpatterns = [
    # TODO create a custom view for profile to check whether superuser access
    url(r'^login/$',LoginUser.as_view(),name="login"),
    url(r'^logout/$',auth_views.logout,{'next_page': settings.LOGOUT_REDIRECT_URL},name="logout"),
    url(r'^register/$',RegisterUser.as_view(),name='register'),
    url(r'^activate/(?P<key>.+)/$',activation,name="activate"),
    url(r'^activation_success/$',TemplateView.as_view(template_name="activation_success.html"),name="activate_success"),
    
    url(r'^profile/$',ProfileView.as_view(),name="profile"),
    url(r'^changepassword/$',ChangePasswordUser.as_view(),name="changepassword"),
    url(r'^editprofile/$',EditUser.as_view(),name="editprofile"),
    
    url(r'^delete/$',DeleteUser.as_view(),name='delete'),

]
    

Product/models.py
from django.db import models

from USER.models import cUser

# Create your models here.
from geoposition.fields import GeopositionField

class Category(models.Model):
	category_name = models.CharField(max_length=255,unique=True)
	def __str__(self):
		return self.category_name

class SubCategory(models.Model):
	category = models.ForeignKey(Category,on_delete=models.CASCADE)
	subcategory_name = models.CharField(max_length=255)
	def __str__(self):
		return self.subcategory_name

class Product(models.Model):
	category = models.ForeignKey(Category)
	subcategory = models.ForeignKey(SubCategory)
	user = models.ForeignKey(cUser,null=True,blank=False,default=None)
	product_name = models.CharField(max_length=255)
	product_estimated_cost = models.CharField(max_length=255)
	product_description = models.TextField(max_length=500)
	product_brochure = models.FileField(upload_to="product_brochure",default=" ",blank=True)
	product_image = models.ImageField(upload_to="product_image")

	product_is_approved = models.BooleanField(default=False)
	product_location = GeopositionField(blank=False)

	def __str__(self):
		return self.product_name

Product/forms.py
from django import forms 

from .models import Category, SubCategory, Product
from django.forms.widgets import CheckboxSelectMultiple

class CatForm(forms.ModelForm):
	class Meta:
		model = Category
		fields = ['category_name']

class SubCatForm(forms.ModelForm):
	class Meta:
		model = SubCategory
		fields = ['category','subcategory_name']

class ProdNewForm(forms.ModelForm):
	class Meta:
		model = Product
		fields = ['category','subcategory','product_name','product_estimated_cost','product_description','product_image','product_location']
	
	def __init__(self, *args, **kwargs):
		super(ProdNewForm, self).__init__(*args, **kwargs)
		# self.fields["subcategory"].widget = CheckboxSlectMultiple()
		self.fields["subcategory"].queryset = SubCategory.objects.none()
		if 'category' in self.data:
			try:
				cat_id = int(self.data.get('category'))
				self.fields['subcategory'].queryset = SubCategory.objects.filter(category=Category.objects.get(id=cat_id)).order_by('subcategory_name')
			except (ValueError, TypeError):
				pass  # invalid input from the client; ignore and fallback to empty queryset
		elif self.instance.pk:
			self.fields['subcategory'].queryset = self.instance.category.subcategory_set.order_by('subcategory_name')

# class ProdForm(forms.ModelForm):
# 	class Meta:
# 		model = Product
# 		fields = ['category_id','subcategory_id','product_name']

Product/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView, View

from .models import Category, SubCategory, Product
from .forms import CatForm, SubCatForm, ProdNewForm 
from django.core.urlresolvers import reverse
from emails.forms import MailsForm

# Create your views here.
# t checklist
# t creation
# t editing
# t deleting
# t listing multiple
# t listing single details
# f payment 

# TODO change success urls to reverse
# check permissions working and test cases for general use cases
# and also edge test cases if it exist 

def mod_response(response):
    response["Cache-Control"] = "no-cache, no-store, must-revalidate" # HTTP 1.1.
    response["Pragma"] = "no-cache" # HTTP 1.0.
    response["Expires"] = "0" # Proxies.
    return response


# used to create new products by the user
class NewItem(CreateView):
    model = Product
    form_class = ProdNewForm    
    template_name = 'Product/additem.html'

    def get(self,request):
        if request.user.is_authenticated():
            return mod_response(super(NewItem,self).get(self,request))
        return mod_response(redirect(reverse('Home:home')))
    
    def post(self,request):
        rval = super(NewItem,self).post(self,request)
        if self.object:
            self.object.user = request.user
            self.object.save()
        return mod_response(rval)
        
    def get_success_url(self):
        return reverse('Product:additem')

# ajax request sub category
def load_subcat(request):
    cat_id = request.GET.get('category_id')
    aa = Category.objects.get(id=int(cat_id))
    subcatlist = SubCategory.objects.filter(category=aa)#.order_by('subcategory_name')
    return render(request, 'Product/productajax.html', {'subcatlist': subcatlist})
    
# used to edit the details of the product by the user
class EditItem(UpdateView):
    template_name = 'Product/additem.html'
    model = Product
    form_class = ProdNewForm
    extra_context = {"work":"edit"}
	
    def get(self,request,pk=-1):
        user = request.user
        pk = int(pk)
        if user.is_authenticated() and pk > 0 :
            if self.model.objects.filter(pk=pk,user=user).first():
                return mod_response(super(EditItem,self).get(self,request))
        return mod_response(redirect(reverse('Home:home')))

    def get_success_url(self):
        return reverse('USER:profile')


	def get_object(self, queryset=None):
		pk = int(self.kwargs['pk'])
		return self.model.objects.get(pk=pk) 


# used to delete the product by a user
class DeleteItem(DeleteView):
    model = Product
    template_name = "Product/delitem.html"

    def get(self,request,pk=-1):
        user = request.user
        pk = int(pk)
        if user.is_authenticated() and pk > 0 :
                if self.model.objects.filter(id=pk).first():
                    return mod_response(super(DeleteItem,self).get(self,request))
        return mod_response(redirect(reverse('Home:home')))

    def get_success_url(self):
        return reverse('USER:profile')

    def get_object(self, queryset=None):
        pk = int(self.kwargs['pk'])
        return self.model.objects.get(id=pk)
    
# used for generic searching the product listing
class ListItemSearch(ListView):
    # add option for sorting the list
    model = Product
    template_name = 'Product/search.html'
    context_object_name = 'object'
    def get(self,request):
        # query = request.GET.get('qry')
        return mod_response(super(ListItemSearch,self).get(self,request))
        # return mod_response(redirect(reverse('Home:home')))
    
    def get_queryset(self):
        rval = super(ListItemSearch,self).get_queryset()
        qry = self.request.GET.get('qry')
        if qry :
            rval = rval.filter(product_name__icontains=qry,product_is_approved=True)
        if not len(rval):
            return None
        return rval
        
    def get_context_data(self,**kwargs):
        t = super(ListItemSearch,self).get_context_data(**kwargs)
        t["query"] = self.request.GET.get('qry')
        return t
    
# used for showing the product page with addtional information
class DetailItem(DetailView):
    model = Product
    template_name = 'Product/det.html'
    def get(self,request,pk=-1):
        if pk > 0:
            return mod_response(super(DetailItem,self).get(self,request))
        return mod_response(redirect(reverse('Home:home')))

    def get_context_data(self,**kwargs):
        t = super(DetailItem,self).get_context_data(**kwargs)
        print(t,")"*30)
        t["contact"] = MailsForm()
        return t

    def post(self,request):
        request.session['yes_mail'] = True
        request.session['mail_type'] = 0
        request.session['reciever'] = self.object.user.email
        request.session['subject'] = "[LootMarket] Contact by user about product" + self.object.product_name
        request.session['sender'] = request.POST.get('sender')
        request.session['message'] = request.POST.get('message')
        return mod_response(redirect(reverse('emails:newmail')))

Product/templates/Product/additem.html
{% extends "base2.html" %}
{% load static %} 
{%block title%}LootMarket - Add Item{%endblock%}

{%block headstyle%}
<style>
    .top-header {
        width: 100%;
        position: fixed;
        display: flex;
        justify-content: center;
        z-index: 6;
        height: 140px;
        background: linear-gradient(0deg, rgba(255, 255, 255, 0.1) 0%, #e4efcd 100%);
    }
    .header-content {
        width: 85%;
        position: absolute;
        height: 140px;
        padding-top: 20px;
    }
    .header-content a {
        /*text-shadow: 0px 0px 3px black;*/
        /*color: black !important;*/
    }



    .home-link {
        display: flex;
        
        position: relative;
    }
    .ull {
        flex: 1;
        margin: 0 auto;
    }
    .home-link-a,.home-link-a:visited{
        width: 294px;
        margin: 0 auto;
        display: block;
        list-style: none;
        font-size: 2.8rem;
        color: black;
        text-align: center;
        text-decoration: none; 
    }



    .glob-links {
        z-index: 5;
        position: fixed;
        top: 0;
        left: 0;
        width: 0;
        height: 100%;
        overflow-x: hidden;
        background-color: #000000cc;
        display: block;
    }
    .close-bar {
        width: 60px;
        color: black;
        font-size: 2.8rem;
        position: fixed;
        left: 20px;
        top: 10px;
        cursor: pointer;
    }
    .llinks {
        margin-top: 100px;
    }

    .link-set,.link-set * {
        text-align: center;
        text-decoration: none;
        /*margin: 10px 0;*/
    }
    .link-set {
        width: 100%;
        display: block;
        padding: 0;
        margin: 0;
        list-style: none;
    }
    .link-set > li {
        /*margin: 10px;*/
        height: 100%;
        width: 100%;
        margin-bottom: 30px;
        position: relative; 
        display: block;  
    }
    .link-set a,.link-set a:visited {
        position: relative;
        height: 100%;
        /*width: 30%;*/
        display: block;
        color: white;
        padding-bottom: 15px;
        /*display: inline;*/
        text-align: center;
        text-decoration: none;
    }
    .link-set a::before {
        left: 0;
        right: 0;
        bottom: 0;
        height: 0;
        content: "";
        position: absolute;
        transition: 0.1s height;
        background-color: white;
        border-top-left-radius: 2px;
        border-top-right-radius: 2px;
    }
    .link-set a.bdd::before {
        bottom: -25px;
        height: 0;
        content: "";
    }
    .link-set a:hover::before {
        height: 5px; 
    }
    .side-right {
        flex-direction: row-reverse;
        margin-left: auto;
    }
    .whh {
        color: white;
    }
    @media only screen and (min-width: 450px) {
        .home-link-a {
            font-size: 4rem !important;
        }
        .close-bar{
            font-size: 4em;
        }
    }



    @media only screen and (min-width: 950px) {
        .glob-links, ..glob-links * {
            all:initial;
        }
        .home-link {
            z-index: 6;
            width: 350px;
            margin: 0 auto;
        }
        .glob-links {
            position: absolute;
            background-color: #00000000;
            width: 90%;
            height: 90px;
            overflow:inherit;
        }
        .close-bar{
            display: none;
        }
        .llinks {
            display: flex;
            flex-flow: row nowrap;
            position: absolute;
            padding: 0;
            margin: 0;
            height: 100%;
            width: 100%;
            align-content: stretch;
        }
        .link-set {
            display: flex;
            list-style: none;
            align-items: stretch;
            justify-content: flex-start;
            flex-flow: row nowrap;
            width: 21%;
            margin-top: 10px;
        }
        .link-set > li {
            flex-basis: 140px;
            margin: 0 10px;
            height: 51px;
            margin-top: 9px; 
            position: relative;   
        }
        .link-set a,.link-set a:visited {
            color: black;
        }
        .link-set a::before {
            background-color: black;
        }
        
    }

</style>
<style>
    .details {
        /*z-index: 19;*/
        position: absolute;
        top: 80px;
        left: 0;
        right: 0;
        bottom: 0;
        padding-left: 20px;
        background: url("{% static "USER/pic4.png" %}") fixed no-repeat center center;
        background-size: cover;
        overflow:scroll; 
    }
    #id_subcategory {
        list-style: none;
    }
    table {
        position: relative;
        top: 42px;
        border-collapse: separate;
        border-spacing: 0 1em;
        width: 80%;
        max-width: 1200px;
    }
    @media only screen and (max-width: 900px) {
        table {
            padding-right: 20px;
        }
    }
    input, select, textarea {
        width: 100%;
    }
    .geoposition-map {
        position: relative;
        top: 35px;
    }
    .geoposition-search {
        display: block;
        position: relative;
        float: none !important;
        width: 100% !important;
        top: 30px !important;
    }
</style>
{%endblock%}


{%block content%}
<header class="top-header">
    <nav class="header-content">
        <div class="home-link">
            <div class="ull">
                <a href="{% url 'Home:home'%}" class="home-link-a">LootMarket</a>
            </div>
        </div>
        <div class="glob-links">
            <span class="close-bar">&#9776;</span>
            <div class="llinks">
                <ul class="link-set side-left">
                    <li><a href="{% url 'Purchase:services'%}">Services</a></li>
                    <li><a href="{% url 'Product:listitemsearch'%}?qry=">Listings</a></li>
                </ul>
                <ul class="link-set side-right">
                    {% if user.is_authenticated%}
                    {%if form.instance.id > 0%}
                        <li><a href="{% url 'Product:additem'%}" class="bdd">New Product</a></li>
                    {%endif%}
                    <li><a href="{%url 'USER:profile'%}">Profile</a></li>
                    <li><a href="{% url 'USER:logout'%}">Logout</a></li>
                    {%endif%}
                </ul>
            </div>
        </div>
    </nav>
</header>

<!--  -->
<div class="details">
    
{%if error%}
{{error}}
{%endif%}
        {%if form%}
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.media}}
        {{form.as_table}}
        <tfoot>
        <tr>
            <td></td>
            <td>
                <button type="submit">Submit</button>
                {%if form.instance.id > 0%}
                        <a href="{% url 'Product:deleteitem' pk=form.instance.id%}"><span class="editc">Delete</span></a>
                {%endif%}
            </td>
        </tr>
        </tfoot>
        </table>
        </form>
        {%endif%}
        <!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> -->

</div>

{%endblock%}



{% block bodyscript %}
  <script>
    $("#id_category").change(function () {
      var url = "{% url 'Product:ajax_load_subcat' %}";//$("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
      var catid = $(this).val();  // get the selected country ID from the HTML input

      // alert(catid);
      // console.log(url);
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'category_id': catid       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_subcategory").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>
<script>
$(function() {
    var bOpened = false;
    var bResize = false;
    var ww = $(window).width();

    $(".close-bar").click(function() {
        if (!bOpened) {
            bOpened = true;
            $(".glob-links").animate({
                width: "200px"
            }, 100, "linear");
            $(this).delay(25).animate({
                left: "160px"
            }, 100, "linear").html("&times;");
        } else {
            bOpened = false;
            $(".glob-links").animate({
                width: "0"
            }, 100, "linear");
            $(this).animate({
                left: "20px"
            }, 100, "linear").html("&#9776;");
        }
            $(this).toggleClass("whh");
    });
    $(window).resize(function() {
        var tw = $(window).width();
        if (!bResize && tw >= 950 && ww < 950) {
            bResize = true;
            $(".glob-links").stop(true, true).css("width", "90%");
            if (bOpened) {
            $(".close-bar").toggleClass("whh");
                $(".close-bar").css("left", "30px").html("&#9776;");
                bOpened = !bOpened;
            }
        } else if (bResize && tw < 950 && ww >= 950) {
            $(".glob-links").stop(true, true).css("width", "0");
            bResize = false;
        }
        ww = tw;
    });

});
</script>
{% endblock %}

Product/templates/Product/delitem.html
{% extends "base2.html" %}
{% load static %} 
{%block title%}LootMarket - Edit Profile{%endblock%}

{%block headstyle%}
<style>
     .top-header {
        width: 100%;
        position: fixed;
        display: flex;
        justify-content: center;
        z-index: 6;
        height: 140px;
        background: linear-gradient(0deg, rgba(255, 255, 255, 0.1) 0%, #e4efcd 100%);
    }
    .header-content {
        width: 85%;
        position: absolute;
        height: 140px;
        padding-top: 20px;
    }
    .header-content a {
        /*text-shadow: 0px 0px 3px black;*/
        /*color: black !important;*/
    }



    .home-link {
        display: flex;
        
        position: relative;
    }
    .ull {
        flex: 1;
        margin: 0 auto;
    }
    .home-link-a,.home-link-a:visited{
        width: 294px;
        margin: 0 auto;
        display: block;
        list-style: none;
        font-size: 2.8rem;
        color: black;
        text-align: center;
        text-decoration: none; 
    }



    .glob-links {
        z-index: 5;
        position: fixed;
        top: 0;
        left: 0;
        width: 0;
        height: 100%;
        overflow-x: hidden;
        background-color: #000000cc;
        display: block;
    }
    .close-bar {
        width: 60px;
        color: black;
        font-size: 2.8rem;
        position: fixed;
        left: 20px;
        top: 10px;
        cursor: pointer;
    }
    .llinks {
        margin-top: 100px;
    }

    .link-set,.link-set * {
        text-align: center;
        text-decoration: none;
        /*margin: 10px 0;*/
    }
    .link-set {
        width: 100%;
        display: block;
        padding: 0;
        margin: 0;
        list-style: none;
    }
    .link-set > li {
        /*margin: 10px;*/
        height: 100%;
        width: 100%;
        margin-bottom: 30px;
        position: relative; 
        display: block;  
    }
    .link-set a,.link-set a:visited {
        position: relative;
        height: 100%;
        /*width: 30%;*/
        display: block;
        color: white;
        padding-bottom: 15px;
        /*display: inline;*/
        text-align: center;
        text-decoration: none;
    }
    .link-set a::before {
        left: 0;
        right: 0;
        bottom: 0;
        height: 0;
        content: "";
        position: absolute;
        transition: 0.1s height;
        background-color: white;
        border-top-left-radius: 2px;
        border-top-right-radius: 2px;
    }
    .link-set a.bdd::before {
        bottom: -25px;
        height: 0;
        content: "";
    }
    .link-set a:hover::before {
        height: 5px; 
    }
    .side-right {
        flex-direction: row-reverse;
        margin-left: auto;
    }
    .whh {
        color: white;
    }
    @media only screen and (min-width: 450px) {
        .home-link-a {
            font-size: 4rem !important;
        }
        .close-bar{
            font-size: 4em;
        }
    }



    @media only screen and (min-width: 1100px) {
        .glob-links, ..glob-links * {
            all:initial;
        }
        .home-link {
            z-index: 6;
            width: 350px;
            margin: 0 auto;
        }
        .glob-links {
            position: absolute;
            background-color: #00000000;
            width: 90%;
            height: 90px;
            overflow:inherit;
        }
        .close-bar{
            display: none;
        }
        .llinks {
            display: flex;
            flex-flow: row nowrap;
            position: absolute;
            padding: 0;
            margin: 0;
            height: 100%;
            width: 100%;
            align-content: stretch;
        }
        .link-set {
            display: flex;
            list-style: none;
            align-items: stretch;
            justify-content: flex-start;
            flex-flow: row nowrap;
            width: 21%;
            margin-top: 10px;
        }
        .link-set > li {
            flex-basis: 140px;
            margin: 0 10px;
            height: 51px;
            margin-top: 9px; 
            position: relative;   
        }
        .link-set a,.link-set a:visited {
            color: black;
        }
        .link-set a::before {
            background-color: black;
        }
        
    }

</style>
<style>
    .details {
        position: absolute;
        top: 140px;
        left: 0;
        right: 0;
        bottom: 0;
        padding-left: 20px;
        background: url("{% static "USER/pic4.png" %}") fixed no-repeat center center;
        background-size: cover;
        overflow-y:scroll;
    }
    table {
        position: relative;
        top: 42px;
        border-collapse: separate;
        border-spacing: 0 1em;
        width: 80%;
        max-width: 1200px;
    }
</style>
{%endblock%}


{%block content%}
<header class="top-header">
    <nav class="header-content">
        <div class="home-link">
            <div class="ull">
                <a href="{% url 'Home:home'%}" class="home-link-a">LootMarket</a>
            </div>
        </div>
        <div class="glob-links">
            <span class="close-bar">&#9776;</span>
            <div class="llinks">
                <ul class="link-set side-left">
                    <li><a href="{% url 'Purchase:services'%}">Services</a></li>
                    <li><a href="{% url 'Product:listitemsearch'%}?qry=">Listings</a></li>
                </ul>
                <ul class="link-set side-right">
                    {% if user.is_authenticated%}
                    <li><a href="{%url 'USER:editprofile'%}" class="bdd">Edit Profile</a></li>
                    <li><a href="{% url 'USER:profile' %}" class="bdd">Profile</a></li>
                    <li><a href="{% url 'USER:logout'%}">Logout</a></li>
                    {%endif%}
                </ul>
            </div>
        </div>
    </nav>
</header>
<!--  -->

<div class="details">
    {%if error%}
        <div class="error-block">
        {{error}}
        </div>
    {%endif%}
    <form method="post" action="">
        {% csrf_token %}
        <p>Deleting {{object}}</p>
        <button type="submit">Delete</button>
    </form>
</div>


{%endblock%}




{% block bodyscript %}
<script>
$(function() {
    var bOpened = false;
    var bResize = false;
    var ww = $(window).width();

    $(".close-bar").click(function() {
        if (!bOpened) {
            bOpened = true;
            $(".glob-links").animate({
                width: "200px"
            }, 100, "linear");
            $(this).delay(25).animate({
                left: "160px"
            }, 100, "linear").html("&times;");
        } else {
            bOpened = false;
            $(".glob-links").animate({
                width: "0"
            }, 100, "linear");
            $(this).animate({
                left: "20px"
            }, 100, "linear").html("&#9776;");
        }
            $(this).toggleClass("whh");
    });
    $(window).resize(function() {
        var tw = $(window).width();
        if (!bResize && tw >= 1100 && ww < 1100) {
            bResize = true;
            $(".glob-links").stop(true, true).css("width", "90%");
            if (bOpened) {
                $(".close-bar").toggleClass("whh");
                $(".close-bar").css("left", "30px").html("&#9776;");
                bOpened = !bOpened;
            }
        } else if (bResize && tw < 1100 && ww >= 1100) {
            $(".glob-links").stop(true, true).css("width", "0");
            bResize = false;
        }
        ww = tw;
    });

});
</script>
{% endblock %}



<div class="details">
    <form method="post" action="">
        {% csrf_token %}
        <p>Deleting {{object}}</p>
        <button type="submit">Delete</button>
    </form>
</div>

Product/templates/Product/productajax.html
<!-- <li><label for="id_subcategory_{{i.id}}"><input id="id_subcategory_{{i.id}}" name="subcategory" type="checkbox" value="{{i.id}}" /> {{i.subcategory_name}}</label></li> -->
<option value="" selected>---------</option>
{%for i in subcatlist %}
    <option value="{{i.id}}">{{i.subcategory_name}}</option>
{%endfor%}